name: linter

on: push
jobs:
  start_linter:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          pip insatll poetry
          make install
      - name: Run linter
        run: |
          make lint
